id: P5EDEE959
initial_creation_type: ocr
source_metadata:
  work_id: http://purl.bdrc.io/resource/WA1KG4853
  instance_id: http://purl.bdrc.io/resource/IE1KG4853
  collection_id: http://purl.bdrc.io/resource/PR0ET009
  language_id: http://purl.bdrc.io/resource/LangBo
  title:
    bo:
    - བོད་ཀྱི་དགོན་སྡེ་ཁག་གཅིག་གི་ངོ་སྤྲོད་མདོར་བསྡུས།
  alt_title:
    en-x-mixed:
    - Bod kyi dgon sde khag gcig gi ṅo sprod mdor bsdus /Blo-bzaṅ-chos-ʼbyor gyis
      brtsams.
    zh-latn-pinyin-x-ndia:
    - 'xue yu ming sheng : zang wen'
  author: http://purl.bdrc.io/resource/P1KG4854
  publisher: UCB-OCR
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  volumes:
    f2204c7767234eaeac5dce1758bd7adc:
      title: པོད ༡་བོད་ཀྱི་དགོན་སྡེ་ཁག་གཅིག་གི་ངོ་སྤྲོད་མདོར་བསྡུས
      volume_number: 1
      base_file: UT1KG4853_I1KG5938_0000.txt
      reference: http://purl.bdrc.io/resource/VL332C00311817EF9C
      image_group: I1KG5938
      quality: Low
  reproductionOf:
  - http://purl.bdrc.io/resource/W1KG4853
  - http://purl.bdrc.io/resource/MW1KG4853
  ocr_software: Namsel
created_at: '2021-12-22T10:43:51.100509'
last_modified_at: '2021-12-22T10:43:51.100516'
statistics:
  total_words: 55545
  total_non_words: 9096
quality:
  non_words_ratio: 0.16
